services:
  - type: web
    name: discussions
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
